# Generated by Django 4.0.4 on 2022-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='end_date',
            field=models.DateTimeField(default=''),
        ),
    ]
