# Generated by Django 4.0.4 on 2022-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
