# Generated by Django 4.0.4 on 2022-05-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.CharField(default=' ', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='neighborhood',
            field=models.CharField(default=' ', max_length=150, unique=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default=' ', max_length=150, unique=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
    ]
