# Generated by Django 4.0.4 on 2022-05-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_address_newuser_neighborhood_newuser_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
