# Generated by Django 4.0.4 on 2022-06-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='newuser',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=150, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='code_vs',
            field=models.CharField(max_length=20, unique=True, verbose_name='Asesor encargado'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='neighborhood',
            field=models.CharField(blank=True, default=' ', max_length=150, unique=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=150, unique=True, verbose_name='Telefono'),
        ),
    ]
