# Generated by Django 4.0.4 on 2022-06-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='code_vs',
        ),
    ]
