# Generated by Django 4.0.5 on 2022-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_newuser_code_vs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='Telefono'),
        ),
    ]
