# Generated by Django 4.0.5 on 2022-06-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='neighborhood',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='Barrio'),
        ),
    ]
