# Generated by Django 4.0.5 on 2022-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_newuser_address_alter_newuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
