# Generated by Django 4.0 on 2022-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_newuser_groups_alter_newuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Empleado'),
        ),
    ]
