# Generated by Django 4.0.4 on 2022-06-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='specialty',
            field=models.CharField(default='', max_length=255, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombre especilista'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Institucion'),
        ),
    ]
