# Generated by Django 4.0.4 on 2022-06-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_specialty_alter_supplier_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
