# Generated by Django 4.0.4 on 2022-06-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplier_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='', max_length=255, verbose_name='Ciudad'),
        ),
    ]
