# Generated by Django 4.0.5 on 2022-06-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_two',
            field=models.CharField(default=' ', max_length=20, verbose_name='Telefono secundario'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefono principal'),
        ),
    ]
