# Generated by Django 4.0.5 on 2022-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplier_phone_two_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Proveedores', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
