# Generated by Django 4.0.5 on 2022-06-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membresia', 'verbose_name_plural': 'Membresia'},
        ),
    ]
