# Generated by Django 4.0.5 on 2022-06-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Cobro', 'verbose_name_plural': 'Cobro'},
        ),
    ]
