# Generated by Django 3.2.13 on 2022-06-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_membership_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='value',
            field=models.FloatField(max_length=10),
        ),
    ]
