# Generated by Django 3.2.13 on 2022-06-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0006_alter_membership_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='value',
            field=models.CharField(help_text='Solo numeros', max_length=10),
        ),
    ]
