# Generated by Django 3.2.13 on 2022-06-22 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_alter_membership_value'),
        ('users', '0013_alter_newuser_password'),
        ('suppliers', '0008_alter_supplier_options'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Clientes', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='customer',
            name='address_to_pay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion para cobrar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_five_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five', to='customers.customer', verbose_name='Afiliado Cinco'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_four_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='customers.customer', verbose_name='Afiliado Cuatro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_one_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to='customers.customer', verbose_name='Afiliado Uno'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_seven_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seven', to='customers.customer', verbose_name='Afiliado Siete'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_six_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='six', to='customers.customer', verbose_name='Afiliado Seis'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_three_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='customers.customer', verbose_name='Afiliado Tres'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_two_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='customers.customer', verbose_name='Afiliado Dos'),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='asesor_id',
            field=models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.newuser', verbose_name='Asesor encargado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector', to='users.newuser', verbose_name='Cobrador'),
        ),
        migrations.AddField(
            model_name='customer',
            name='creator_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='users.newuser', verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizacion'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gener',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO'), ('OTRO', 'OTRO')], default=' ', max_length=100, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_collector',
            field=models.BooleanField(default=False, verbose_name='Cobro RF.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership', verbose_name='Membresia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neigbord',
            field=models.CharField(blank=True, default=' ', max_length=20, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$320000$iNI4Mj0nXAjmeRiNnWwZsG$M5fBt/nVaKFdXO35PW+S/paCXgaOcdFZsI6TpAOtx84=', max_length=255, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_id',
            field=models.CharField(default=' ', max_length=20, unique=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 22, 16, 9, 3, 224165), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status_membership',
            field=models.CharField(choices=[('COBRO', 'COBRO'), ('PAGO', 'PAGO'), ('INCONVENIENTE', 'INCONVENIENTE'), ('INACTIVO', 'INCATIVO')], default='DIGITADO', max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='way_to_pay',
            field=models.CharField(blank=True, choices=[('1', 'Contado'), ('2', 'Quincenal'), ('3', 'Mensual'), ('4', 'Anual')], max_length=255, null=True, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aporte')),
                ('pay_method', models.CharField(choices=[('BANCOLOMBIA', 'BANCOLOMBIA'), ('BANCO DE BOG.', 'BANCO DE BOG.'), ('DAVIVIENDA', 'DAVIVIENDA'), ('EFECTIVO', 'EFECTIVO'), ('DATAFONO', 'DATAFONO'), ('OTRO', 'OTRO')], default='DIGITADO', max_length=100, verbose_name='Metodo de pago')),
                ('full_payment', models.DecimalField(blank=True, decimal_places=0, help_text='Solo numeros', max_digits=10, verbose_name='Total abono')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Saldo')),
                ('status', models.CharField(choices=[('DIGITADO', 'DIGITADO'), ('CONTABILIZADO', 'CONTABILIZADO'), ('REVISADO', 'REVISADO')], default='DIGITADO', max_length=100, verbose_name='Estado admin')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.newuser', verbose_name='Creado por')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Recibos',
                'verbose_name_plural': 'Recibos',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio solicitud')),
                ('type_appointment', models.CharField(choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('3', 'Tipo 3')], max_length=255, verbose_name='Tipo de cita')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cita')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.newuser', verbose_name='Creado por')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Citas',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
