# Generated by Django 4.0.4 on 2022-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
