# Generated by Django 3.2.13 on 2022-06-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20220623_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_descount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Solo numeros', max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city_pay',
            field=models.CharField(blank=True, choices=[('ARMENIA', 'ARMENIA'), ('CARTAGO', 'CARTAGO'), ('QUIMBAYA', 'QUIMBAYA'), ('PEREIRA', 'PEREIRA')], default=' ', max_length=20, verbose_name='Ciudad cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono Opcional'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 10, 47, 42, 198737), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
