# Generated by Django 3.2.13 on 2022-06-23 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20220623_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='type_appointment',
            field=models.CharField(choices=[('AFILIACION', 'AFILIACION'), ('CITA', 'CITA'), ('INFORMACION', 'INFORMACION'), ('OTROS', 'OTROS')], default='CITA', max_length=255, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 23, 11, 57, 4, 452418), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
