# Generated by Django 4.0.4 on 2022-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(default=' ', max_length=3, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='asesor_id',
            field=models.CharField(default=' ', max_length=20, verbose_name='Asesor encargado'),
        ),
    ]
