# Generated by Django 4.0.4 on 2022-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_age_customer_asesor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='person_id',
            field=models.CharField(default=' ', max_length=20, verbose_name='Cedula'),
        ),
    ]
