# Generated by Django 4.0.4 on 2022-06-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default=' ', max_length=20, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neigbord',
            field=models.CharField(default=' ', max_length=20, verbose_name='Barrio'),
        ),
    ]
