# Generated by Django 3.2.13 on 2022-06-24 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_auto_20220623_1541'),
        ('customers', '0009_alter_customer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.service', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 11, 21, 27, 504696), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, verbose_name='Valor a pagar ='),
        ),
    ]
