# Generated by Django 4.0.4 on 2022-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_city_customer_is_active_customer_neigbord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.IntegerField(choices=[(1, 'Bipers'), (2, 'Pluss'), (3, 'Clasic'), (4, 'Express')], default=1),
        ),
    ]
