# Generated by Django 4.0.4 on 2022-06-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('customers', '0010_customer_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
        migrations.AddField(
            model_name='customer',
            name='membership_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership'),
        ),
    ]
