# Generated by Django 3.2.13 on 2022-06-24 20:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_newuser_password'),
        ('memberships', '0007_alter_membership_value'),
        ('suppliers', '0012_auto_20220623_1541'),
        ('customers', '0010_auto_20220624_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 15, 16, 2, 900451), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.CreateModel(
            name='HistoricalInvoice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de aporte')),
                ('pay_method', models.CharField(choices=[('BANCOLOMBIA', 'BANCOLOMBIA'), ('BANCO DE BOG.', 'BANCO DE BOG.'), ('DAVIVIENDA', 'DAVIVIENDA'), ('EFECTIVO', 'EFECTIVO'), ('DATAFONO', 'DATAFONO'), ('OTRO', 'OTRO')], default='DIGITADO', max_length=100, verbose_name='Metodo de pago')),
                ('full_payment', models.DecimalField(blank=True, decimal_places=0, help_text='Solo numeros', max_digits=10, verbose_name='Total abono')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=10, verbose_name='Saldo')),
                ('status', models.CharField(choices=[('DIGITADO', 'DIGITADO'), ('CONTABILIZADO', 'CONTABILIZADO'), ('REVISADO', 'REVISADO')], default='DIGITADO', max_length=100, verbose_name='Estado admin')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.newuser', verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.newuser')),
            ],
            options={
                'verbose_name': 'historical Recibos',
                'verbose_name_plural': 'historical Recibos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('person_id', models.CharField(db_index=True, default=' ', max_length=20, verbose_name='Cedula')),
                ('is_collector', models.BooleanField(default=False, verbose_name='Cobro RF.')),
                ('way_to_pay', models.CharField(blank=True, choices=[('1', 'Contado'), ('2', 'Quincenal'), ('3', 'Mensual'), ('4', 'Anual')], max_length=255, null=True, verbose_name='Tipo de pago')),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 24, 15, 16, 2, 900451), null=True, verbose_name='Fecha de Suscripcion')),
                ('value', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=10, verbose_name='Valor a pagar =')),
                ('password', models.CharField(default='pbkdf2_sha256$320000$iNI4Mj0nXAjmeRiNnWwZsG$M5fBt/nVaKFdXO35PW+S/paCXgaOcdFZsI6TpAOtx84=', max_length=255, verbose_name='Password')),
                ('address_to_pay', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion para cobrar')),
                ('payment_descount', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Solo numeros', max_digits=10, verbose_name='Descuento')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('city', models.CharField(blank=True, choices=[('ARMENIA', 'ARMENIA'), ('CARTAGO', 'CARTAGO'), ('QUIMBAYA', 'QUIMBAYA'), ('PEREIRA', 'PEREIRA')], default=' ', max_length=20, verbose_name='Ciudad')),
                ('city_pay', models.CharField(blank=True, choices=[('ARMENIA', 'ARMENIA'), ('CARTAGO', 'CARTAGO'), ('QUIMBAYA', 'QUIMBAYA'), ('PEREIRA', 'PEREIRA')], default=' ', max_length=20, verbose_name='Ciudad cobro')),
                ('neigbord', models.CharField(blank=True, default=' ', max_length=20, verbose_name='Barrio')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('phone_contact', models.CharField(blank=True, max_length=20, verbose_name='Telefono Opcional')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('createdAt', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Cobro')),
                ('endsAt', models.DateTimeField(blank=True, null=True, verbose_name='Finalizacion')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Titular')),
                ('status_membership', models.CharField(choices=[('COBRO', 'COBRO'), ('PAGO', 'PAGO'), ('INCONVENIENTE', 'INCONVENIENTE'), ('INACTIVO', 'INCATIVO')], default='DIGITADO', max_length=100, verbose_name='Estado')),
                ('gener', models.CharField(blank=True, choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO'), ('OTRO', 'OTRO')], default=' ', max_length=100, verbose_name='Genero')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('affiliate_five_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Cinco')),
                ('affiliate_four_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Cuatro')),
                ('affiliate_one_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Uno')),
                ('affiliate_seven_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Siete')),
                ('affiliate_six_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Seis')),
                ('affiliate_three_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Tres')),
                ('affiliate_two_customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Afiliado Dos')),
                ('asesor_id', models.ForeignKey(blank=True, db_constraint=False, default='2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.newuser', verbose_name='Asesor encargado')),
                ('collector', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.newuser', verbose_name='Cobrador')),
                ('creator_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.newuser', verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.newuser')),
                ('membership_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='memberships.membership', verbose_name='Membresia')),
            ],
            options={
                'verbose_name': 'historical Clientes',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAppointment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio solicitud')),
                ('type_appointment', models.CharField(choices=[('AFILIACION', 'AFILIACION'), ('CITA', 'CITA'), ('INFORMACION', 'INFORMACION'), ('OTROS', 'OTROS')], default='CITA', max_length=255, verbose_name='Tipo de cita')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha cita')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('is_confirm', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('is_cancel', models.BooleanField(default=False, verbose_name='Cancelada')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.newuser', verbose_name='Creado por')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.newuser')),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.service', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'historical Citas',
                'verbose_name_plural': 'historical Citas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
