# Generated by Django 4.0.4 on 2022-06-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_is_active'),
        ('customers', '0011_remove_customer_membership_customer_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership', verbose_name='Membresia'),
        ),
    ]
