# Generated by Django 4.0 on 2022-07-03 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20220624_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='buffer_full_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Ultimo abono'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buffer_full_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Ultimo abono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 3, 9, 53, 55, 885156), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 3, 9, 53, 55, 885156), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='full_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Solo numeros', max_digits=10, verbose_name='Total abono'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='full_payment',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Solo numeros', max_digits=10, verbose_name='Total abono'),
        ),
    ]
