# Generated by Django 4.0 on 2022-07-04 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_historicalinvoice_buffer_full_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 4, 12, 1, 24, 696300), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 4, 12, 1, 24, 696300), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
