# Generated by Django 4.0 on 2022-07-05 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 5, 16, 30, 3, 38088), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 5, 16, 30, 3, 38088), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalinvoice',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Saldo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Saldo'),
        ),
    ]
