# Generated by Django 4.0 on 2022-07-08 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_descount',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', help_text='Solo numeros', max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 17, 55, 44, 541210), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='payment_descount',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', help_text='Solo numeros', max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 17, 55, 44, 541210), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
