# Generated by Django 4.0.5 on 2022-06-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0014_alter_customer_asesor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='asesor_id',
            field=models.ForeignKey(default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asesor encargado'),
        ),
    ]
