# Generated by Django 4.0 on 2022-07-26 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 26, 12, 1, 52, 284575), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 12, 1, 52, 284163), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Cobro'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='endsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 26, 12, 1, 52, 284575), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 12, 1, 52, 284163), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
