# Generated by Django 4.0.5 on 2022-06-09 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0016_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='affiliate',
            field=models.CharField(blank=True, max_length=255, verbose_name='Afiliado'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_cancel',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='Confirmada'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='about',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha finalizacion'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio solicitud'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='type_appointment',
            field=models.CharField(choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('3', 'Tipo 3')], max_length=255, verbose_name='Tipo de cita'),
        ),
    ]
