# Generated by Django 4.0.5 on 2022-06-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_remove_appointment_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='author',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
    ]
