# Generated by Django 4.0 on 2022-07-26 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_alter_customer_createdat_alter_customer_endsat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 26, 15, 2, 53, 978595), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 15, 2, 53, 978292), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='endsAt',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 7, 26, 15, 2, 53, 978595), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 26, 15, 2, 53, 978292), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
