# Generated by Django 4.0 on 2022-07-27 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_customer_endsat_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 27, 16, 9, 17, 869577), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 27, 16, 9, 17, 869307), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='endsAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 27, 16, 9, 17, 869577), null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 27, 16, 9, 17, 869307), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
