# Generated by Django 4.0.5 on 2022-06-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_appointment_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='affiliate',
            new_name='affiliate_customer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='affiliate',
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
            ],
        ),
    ]
