# Generated by Django 4.0.5 on 2022-06-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_rename_affiliate_customer_affiliate_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='customer',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='customer',
            field=models.ManyToManyField(to='customers.customer', verbose_name='Cliente'),
        ),
    ]
