# Generated by Django 4.0.5 on 2022-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_remove_affiliate_customer_affiliate_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='customer',
            new_name='customers',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='headline',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
