# Generated by Django 4.0.5 on 2022-06-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_rename_customer_affiliate_customers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affiliate',
        ),
    ]
