# Generated by Django 4.0.5 on 2022-06-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_delete_affiliate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='affiliate_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_five_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='five', to='customers.customer', verbose_name='Afiliado Cinco'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_four_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='customers.customer', verbose_name='Afiliados Cuatro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_one_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to='customers.customer', verbose_name='Afiliado Uno'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_three_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='customers.customer', verbose_name='Afiliados Tres'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_two_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='customers.customer', verbose_name='Afiliados Dos'),
        ),
    ]
