# Generated by Django 4.0.5 on 2022-06-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_remove_customer_affiliate_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='way_to_pay',
            field=models.CharField(choices=[('1', 'Contado'), ('2', 'Quincenal'), ('3', 'Mensual'), ('4', 'Anual')], max_length=255, null=True, verbose_name='Tipo de pago'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
    ]
