# Generated by Django 4.0.5 on 2022-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_customer_way_to_pay_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
