# Generated by Django 4.0.5 on 2022-06-10 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_customer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='affiliate_seven_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seven', to='customers.customer', verbose_name='Afiliado Cinco'),
        ),
        migrations.AddField(
            model_name='customer',
            name='affiliate_six_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='six', to='customers.customer', verbose_name='Afiliado Cinco'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 10, 16, 31, 44, 28919), null=True, verbose_name='Fecha de inicio'),
        ),
    ]
