# Generated by Django 4.0.5 on 2022-06-11 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_customer_value_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 11, 14, 16, 7, 188077), null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor'),
        ),
    ]
