# Generated by Django 4.0.5 on 2022-06-13 15:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0031_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 13, 10, 49, 53, 192450), null=True, verbose_name='Fecha de inicio'),
        ),
    ]
