# Generated by Django 4.0.5 on 2022-06-14 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_alter_appointment_added_by_alter_customer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(null=True, verbose_name='Finaclizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Inicio Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 8, 1, 44, 525839), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
