# Generated by Django 4.0.5 on 2022-06-14 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membership_options'),
        ('customers', '0036_customer_endsat_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='membership_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membership', verbose_name='Membresia'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 8, 36, 25, 45788), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='way_to_pay',
            field=models.CharField(blank=True, choices=[('1', 'Contado'), ('2', 'Quincenal'), ('3', 'Mensual'), ('4', 'Anual')], max_length=255, null=True, verbose_name='Tipo de pago'),
        ),
    ]
