# Generated by Django 4.0.5 on 2022-06-14 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0037_alter_customer_createdat_alter_customer_endsat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='affiliate_four_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four', to='customers.customer', verbose_name='Afiliado Cuatro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='affiliate_three_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='customers.customer', verbose_name='Afiliado Tres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='affiliate_two_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='customers.customer', verbose_name='Afiliado Dos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 9, 15, 50, 494629), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
