# Generated by Django 4.0.5 on 2022-06-14 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0038_alter_customer_affiliate_four_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateField(blank=True, null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 13, 57, 13, 606909), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='value',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisional', models.SmallIntegerField(blank=True, null=True, verbose_name='Nro. Provisional ')),
                ('contribution_date', models.DateField(blank=True, null=True, verbose_name='Fecha aporte ')),
                ('full_payment', models.FloatField(blank=True, null=True, verbose_name='Total abono')),
                ('balance', models.FloatField(blank=True, null=True, verbose_name='Saldo')),
                ('status', models.CharField(choices=[('DIGITADO', 'DIGITADO'), ('CONTABILIZADO', 'CONTABILIZADO'), ('REVISADO', 'REVISADO')], default='DIGITADO', max_length=100)),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Notas')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio solicitud')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Recibos',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
