# Generated by Django 4.0.5 on 2022-06-14 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0039_alter_customer_createdat_alter_customer_endsat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 13, 57, 39, 334754), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
