# Generated by Django 4.0.5 on 2022-06-14 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0040_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Cobro'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='endsAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizacion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 14, 1, 30, 286194), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contribution_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha aporte '),
        ),
    ]
