# Generated by Django 4.0.5 on 2022-06-14 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0041_alter_customer_createdat_alter_customer_endsat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 14, 47, 56, 20824), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
