# Generated by Django 4.0.5 on 2022-06-14 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0044_customer_status_membership_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gener',
            field=models.CharField(choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO'), ('OTRO', 'OTRO')], default=' ', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 15, 30, 47, 489676), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
