# Generated by Django 4.0.5 on 2022-06-14 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0045_customer_gener_alter_customer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector', to=settings.AUTH_USER_MODEL, verbose_name='Cobrador'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gener',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'FEMENINO'), ('MASCULINO', 'MASCULINO'), ('OTRO', 'OTRO')], default=' ', max_length=100, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 15, 44, 0, 237489), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
