# Generated by Django 4.0.5 on 2022-06-14 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0046_customer_collector_alter_customer_gener_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_collector',
            field=models.BooleanField(default=False, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 14, 15, 53, 46, 61631), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
