# Generated by Django 4.0.5 on 2022-06-15 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0047_customer_is_collector_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_collector',
            field=models.BooleanField(default=False, verbose_name='Cobro RF.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 7, 4, 11, 595134), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
