# Generated by Django 4.0.5 on 2022-06-15 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0055_alter_customer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 7, 56, 54, 208595), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
