# Generated by Django 4.0.5 on 2022-06-15 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0056_customer_added_by_alter_customer_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='added_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='creator_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='customers.customer', verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 8, 8, 15, 783433), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
