# Generated by Django 4.0.5 on 2022-06-15 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0057_remove_customer_added_by_customer_creator_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 8, 18, 6, 16807), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
