# Generated by Django 4.0.5 on 2022-06-15 13:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0061_alter_customer_start_date_alter_invoice_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_to_pay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion para cobrar'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 8, 55, 40, 704347), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
