# Generated by Django 4.0.5 on 2022-06-15 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0062_customer_address_to_pay_alter_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cita'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='person_id',
            field=models.CharField(default=' ', max_length=20, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 15, 16, 26, 16, 555527), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
