# Generated by Django 4.0.5 on 2022-06-16 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0064_customer_birth_day_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 7, 26, 55, 301400), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
