# Generated by Django 4.0.5 on 2022-06-16 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0065_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(blank=True, default='', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 8, 5, 56, 108470), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
