# Generated by Django 4.0.5 on 2022-06-16 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0066_alter_customer_age_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 8, 6, 20, 923403), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
