# Generated by Django 4.0.5 on 2022-06-16 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0068_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default='', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 16, 10, 10, 28, 923259), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
