# Generated by Django 3.2.13 on 2022-06-17 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0069_alter_customer_age_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 17, 17, 2, 54, 165018), null=True, verbose_name='Fecha de Suscripcion'),
        ),
    ]
