# Generated by Django 3.2.13 on 2022-06-21 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0071_alter_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 21, 11, 43, 40, 49964), null=True, verbose_name='Fecha de Suscripcion'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='value',
            field=models.FloatField(blank=True, help_text='Solo numeros', max_length=10, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='full_payment',
            field=models.FloatField(blank=True, help_text='Solo numeros', null=True, verbose_name='Total abono'),
        ),
    ]
